version: "3"
services:
  mysql_db:
    build: docker/mysql_db/
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secretpass
    volumes:
      - mysql_db_path:/var/lib/mysql
    ports:
      - 13306:3306
volumes:
  mysql_db_path:
